version: 2

general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: amomum/ubuntu_eclipse_asan:0.1
    steps:
      - checkout
      - run:
          name: Compile with eclipse and run tests
          when: always
          command: chmod +x ./example_project/run_tests.sh && ./example_project/run_tests.sh 
          no_output_timeout: 1m
